# Generated by Django 5.2.8 on 2025-12-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_animal_id_alter_animal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='type',
        ),
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='dewormed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='animals_photos/'),
        ),
        migrations.AddField(
            model_name='animal',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Unknown', 'Unknown')], default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Rabbit', 'Rabbit'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='animal',
            name='sterilized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='vaccinated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Adopted', 'Adopted')], default='Available', max_length=10),
        ),
    ]
