# Generated by Django 5.2.8 on 2025-12-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_remove_animal_photo_remove_animal_species_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='submitted_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='animal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('adopted', 'Adopted'), ('pending', 'Pending Approval')], default='available', max_length=20),
        ),
    ]
